### ISSUE TITLE
sh: failover: unknown operand

### ISSUE THREAD

**Issue by vchatela** [fire1ce/UDM-Failover-Telegram-Notifications#1]
Hello,
I used your script  but I've got this error on UDM Pro. 
Before I needed to move from /bin/bash to /bin/sh as bash is not available on UDM Pro with latest firmware.

```
$ /mnt/data/UDMP-Failover-Telegram-Notifications/failover-notifications.sh
Starting failover notifications. Current interface: eth8 with external IP: XX.XX.XX.XX
sh: failover: unknown operand
```
What's wrong ?
Thx

**Comment by vchatela** [comment]
I managed to fix with : 
```
case "$telegram_notification" in
	*"\"ok\":false"*) echo "Error! Telegram notification failed" ; echo ${telegram_notification=} ;;
	*) ;;
esac
```
instead of `if [[ ]]`

**Comment by fire1ce** [comment]
hey, i've wrote it in bash. sh won't support "[[ ]]" if statements. i need to adopt it for sh. i'll do it this week. Don't close the issue.

**Comment by fire1ce** [comment]
@vchatela 
I've updated the scripts including the install and readme to `sh`instead on `bash`. 
Advice to reinstall the script. you can use the readme how to `uninstall` then use the install script.
